name: BIPNet
dependencies:
  # core
  - pytorch::pytorch=1.11.0=py3.10_cuda11.5_cudnn8.3.2_0
  - conda-forge::pytorch-lightning
  - conda-forge::numpy

  # vision and isp
  - pytorch::torchvision
  - fastai::opencv-python-headless
  - conda-forge::exifread

  # cupy and its extensions
  - conda-forge::cupy
  - conda-forge::cudnn
  - conda-forge::cutensor
  - conda-forge::nccl

  # Get newest copy of packages not on conda-forge
  - conda-forge::pip
  - pip:
    - lpips
